scrape_configs:
  - job_name: "spring-boot-application"
    scheme: https
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["mateusnavarro77.xyz"]
        labels:
          application: "Projeto Cybersec - Task Manager Rest API (Producao)"
